_target_: birdset.datamodule.LoadersConfig
train:
  _target_: birdset.datamodule.LoaderConfig
  batch_size: 128
  shuffle: True
  num_workers: 32
  drop_last: False
  persistent_workers: True
  pin_memory: True

valid:
  _target_: birdset.datamodule.LoaderConfig
  batch_size: 128
  shuffle: False
  num_workers: 32
  drop_last: False
  persistent_workers: True
  pin_memory: False

test:
  _target_: birdset.datamodule.LoaderConfig
  batch_size: 128
  shuffle: False
  num_workers: 32
  drop_last: False
  persistent_workers: False
  pin_memory: False