defaults:
  - network: ppnet_convnext.yaml

task: multilabel
class_weights_loss: ${datamodule.dataset.class_weights_loss}
prediction_table: False
num_gpus: ${trainer.devices}

training_phase: null

num_prototypes: 2055
prototype_layer_stride: 1

train_classifier_only: True
last_layer_fixed: False
freeze_incorrect_class_connections: False
pruning_threshold: null

subtractive_margin: False

max_epochs_warm: 10
max_epochs_joint: null
max_epochs_joint_with_last_layer: null
max_epochs_last_layer: null

optimizer:
  _target_: torch.optim.AdamW

weight_decay: 1e-4

warm_optimizer_lrs:
  add_on_layers: 3e-2
  prototype_vectors: 0.05
  frequency_weights: null #5e-4 #1e-3
  warm_last_layer_lr: 5e-4

joint_optimizer_lrs:
  backbone_model: null #5e-4
  add_on_layers: null #3e-2
  prototype_vectors: null #1e-2
  frequency_weights: null #5e-4 #1e-3
  joint_last_layer_lr: null #1e-3 #5e-2

last_layer_optimizer_lr: null #1e-4 #1e-3

coefs:
  cross_entropy_loss: 1.0
  cluster_cost: null #-0.25
  separation_cost: null #0.05
  l1_loss_last_layer: null #0.4
  zero_weights_loss_last_layer: null #3.0
  l1_loss_frequency_weights: null #0.4
  orthogonality_loss: 1.0

loss:
  _target_: audioprotopnet.modules.losses.asymmetric_loss.AsymmetricLossMultiLabel
  
lr_scheduler:
  scheduler:
    _target_: transformers.get_cosine_schedule_with_warmup
  extras:
    interval: step
    warmup_ratio: 0.05

metrics: 
  main: 
    _target_: birdset.modules.metrics.cmAP
    num_labels: ${datamodule.dataset.n_classes}
    thresholds: null
  val_best: 
    _target_: "torchmetrics.MaxMetric"
  additional: 
    MultilabelAUROC:
      _target_: "torchmetrics.classification.AUROC"
      task: "multilabel"
      num_labels: ${datamodule.dataset.n_classes} 
      average: "macro"
      thresholds: null
    T1Accuracy:
      _target_: birdset.modules.metrics.TopKAccuracy
      topk: 1
    T3Accuracy:
      _target_: birdset.modules.metrics.TopKAccuracy
      topk: 5
    mAP:
      _target_: birdset.modules.metrics.mAP
      num_labels: ${datamodule.dataset.n_classes}    
      thresholds: null
  eval_complete:
    pcmAP:
      _target_: birdset.modules.metrics.pcmAP
      num_labels: ${datamodule.dataset.n_classes}
      padding_factor: 5
      average: macro
      thresholds: null
    cmAP5:
      _target_: birdset.modules.metrics.cmAP5
      num_labels: ${datamodule.dataset.n_classes}
      sample_threshold: 5
      thresholds: null

output_activation: 
  _target_: "torch.sigmoid"

logging_params:
  on_step: False
  on_epoch: True
  sync_dist: False
  prog_bar: True  

