root_dir: ${oc.env:PROJECT_ROOT}
work_dir: ${hydra:runtime.cwd}

# dynamic output directory
# store ckpts etc. 
output_dir: ${hydra:runtime.output_dir}
prototype_files_dir: null # Only required for local analysis
local_analysis_dir: null # Only required for local analysis

# data directory
dataset_path: ${paths.root_dir}/data_birdset/${datamodule.dataset.dataset_name}
model_path: ${paths.root_dir}/data_birdset/models/
background_path: ${paths.root_dir}/data_birdset/background_noise/dcase18_unpacked_wav

# logging directory, has to be static to work properly
log_dir: ${paths.root_dir}/logs/

